#!/bin/bash
# Disable conky and composite manager
# for better move experience

start() {
  pkill compton
  exit
}

stop() {
  compton &
  exit
}

help() {
  echo "Movie Mode:"
  echo "   (re)start: moviemode"
  echo "   stop:      moviemode -s"
  exit
}


case "$1" in
  "")   start ;;
"-s")   stop ;;
    *)  help ;;
  esac
